export type User = {
	id: number;
	name: string;
	books: Book[];
};

export type Book = {
	isAvailable: boolean;
	id: number;
	name: string;
};

// Generated by https://quicktype.io

export type BookExchange = {
	date: string;
	id: number;
	typeBookExchange: TypeBookExchange;
	nameBook: string;
	nameUser: string;
};

export enum TypeBookExchange {
	Lend = "lend",
	Return = "return",
}
